import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/website/global/Header";
import Footer from "@/components/website/global/Footer";
import ReduxProvidor from "@/redux/ReduxProvidor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <ReduxProvidor>
          <Header />
          <main className="min-h-full flex flex-col">{children}</main>
          <Footer />
        </ReduxProvidor>

      </body>

    </html>
  );
}
